package com.botdiril.command.gambling;

import com.botdiril.framework.command.Command;
import com.botdiril.framework.command.CommandCategory;
import com.botdiril.framework.command.context.CommandContext;
import com.botdiril.framework.command.invoke.CmdInvoke;
import com.botdiril.discord.framework.command.context.DiscordCommandContext;
import com.botdiril.framework.response.ResponseEmbed;
import com.botdiril.userdata.icon.Icons;
import com.botdiril.util.BotdirilFmt;

@Command(value = "jackpot", category = CommandCategory.GAMBLING, description = "Shows the jackpot.")
public class CommandJackpot
{
    @CmdInvoke
    public static void tellJackpot(CommandContext co)
    {
        var eb = new ResponseEmbed();
        eb.setTitle("Your Jackpot Stats");
        eb.setDescription("Each user has their own jackpot pool generated by losing keks while gambling.");
        eb.setColor(0x008080);
        eb.addField("Jackpot", BotdirilFmt.amountOf(co.userProperties.getJackpot(), Icons.KEK), false);
        eb.addField("How much will stay after paying out the jackpot", BotdirilFmt.amountOf(co.userProperties.getJackpotStored(), Icons.KEK), false);

        if (co instanceof DiscordCommandContext dcc)
        {
            eb.setAuthor("%s#%s".formatted(dcc.caller.getName(), dcc.caller.getDiscriminator()));
            eb.setThumbnail(dcc.caller.getEffectiveAvatarUrl());
        }
        else
        {
            eb.setThumbnail(co.botIconURL);
        }

        co.respond(eb);
    }
}
