package com.botdiril.command.gambling;

import net.dv8tion.jda.api.EmbedBuilder;

import com.botdiril.framework.command.CommandContext;
import com.botdiril.framework.command.Command;
import com.botdiril.framework.command.CommandCategory;
import com.botdiril.framework.command.invoke.CmdInvoke;
import com.botdiril.userdata.icon.Icons;

@Command(value = "jackpot", category = CommandCategory.GAMBLING, description = "Shows the jackpot.")
public class CommandJackpot
{
    @CmdInvoke
    public static void tellJackpot(CommandContext co)
    {
        var eb = new EmbedBuilder();
        eb.setTitle("Jackpot Stats");
        eb.setDescription("Each user has their own jackpot pool generated by losing keks while gambling.");
        eb.setColor(0x008080);
        eb.addField("Jackpot",
            String.format("%d %s", co.po.getJackpot(), Icons.KEK),
            false);
        eb.addField("How much will stay after paying out the jackpot",
            String.format("%d %s", co.po.getJackpotStored(), Icons.KEK),
            false);

        co.respond(eb);
    }
}
